import type { NextPage } from 'next'
import Head from 'next/head'
import { WelcomeStep } from '../components/steps/WelcomeStep'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Clubhouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      <WelcomeStep />

    </div>
  )
}

export default Home
